version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  barograph:
    image: walteraa/barograph:latest
    container_name: "barograph"
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    ports:
      - 8080:8080
  barograph_screen:
    image: walteraa/barograph_screen:latest
    container_name: "barograph_screen"
    environment:
      - BACKEND_PORT=8080
      - BACKEND_HOST=barograph
    ports:
      - 9000:9000
